services:
  api:
    build: .
#    command:
#      - uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/personalised_nudges
    ports:
      - '8000:8000'
    env_file:
      - .env
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_HOST=postgres
#      - POSTGRES_PORT=5432
#      - DB_NAME=postgres
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always


volumes:
  postgres_data: